version: '3.9'
services:
  web:
    image: louislam/dockge:latest
    container_name: dockge
    restart: always
    ports:
      - ${APP_PORT}:5001
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  default:
    driver: bridge
