version: '3.9'
services:
  web:
    image: louislam/dockge:latest
    container_name: dockge
    restart: always
    ports:
      - ${APP_PORT}:5001
    networks:
      - default
    volumes:
      - docker_dockge_data:/app/data
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  default:
    name: docker_dockge_network
    driver: bridge

volumes:
  data:
    name: docker_dockge_data
    driver: local
