services:
  dockge:
    container_name: ${DOCKGE_CONTAINER_NAME}
    image: ${DOCKGE_IMAGE_NAME}:${DOCKGE_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}
    ports:
      - ${DOCKGE_HTTP_PORT}:5001
    volumes:
      - default:/app/data
      - ${DOCKGE_DATA_DIR}:/app/data
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
    networks:
      - default

networks:
  default:
    name: ${DOCKGE_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${DOCKGE_CONTAINER_NAME}_data
    driver: local